version: "3.9"

services:
  app:
    build:
      #use current directory
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    #run service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
